ARDUINO_CLI := arduino-cli

PROFILE	= esp32s3-ospi
FQBN	= esp32.esp32.esp32s3
INO	= ats-mini.ino
ELF	= ./build/$(FQBN)/$(INO).elf
PORT	?= /dev/cu.usbmodem1101

DEBUG_LEVEL ?= 0

#
# HALF_STEP       : Enable encoder half-steps
# BLE_POWER_LEVEL : BLE TX power level, for example ESP_PWR_LVL_N12
# WIFI_POWER_LEVEL: WiFi TX power level, for example WIFI_POWER_13dBm
#
DEFINES = -DDEBUG=$(DEBUG_LEVEL)

ifdef LILYGO_SI473X
        DEFINES += -DLILYGO_SI473X
endif

ifdef HALF_STEP
        DEFINES += -DHALF_STEP
endif

ifdef BLE_POWER_LEVEL
        DEFINES += -DBLE_POWER_LEVEL=$(BLE_POWER_LEVEL)
endif

ifdef WIFI_POWER_LEVEL
        DEFINES += -DWIFI_POWER_LEVEL=$(WIFI_POWER_LEVEL)
endif

OPTIONS = \
	--build-property "compiler.cpp.extra_flags=$(DEFINES)" \
	--warnings all

HEADERS = \
	Common.h Themes.h Menu.h Storage.h tft_setup.h Rotary.h \
	Utils.h Button.h EIBI.h Remote.h BleMode.h BlePeripheral.h \
	BleUartPeripheral.h BleCentral.h BleHidCentral.h \
	SI4735-fixed.h patch_init.h Splash.h

SRC = \
	$(INO) Utils.cpp Rotary.cpp Button.cpp Draw.cpp Menu.cpp \
	Station.cpp Battery.cpp Storage.cpp Themes.cpp Remote.cpp \
	Network.cpp Splash.cpp EIBI.cpp Scan.cpp About.cpp BleMode.cpp \
	BlePeripheral.cpp BleUartPeripheral.cpp \
	BleCentral.cpp BleHidCentral.cpp \
	Layout-Default.cpp Layout-SMeter.cpp

all: build

help:
	@echo 'Run this command to upload the firmware to your radio:'
	@echo
	@echo '  make upload PORT=/dev/cu.usbmodem1101'
	@echo

build: $(ELF)

$(ELF): $(INO) $(SRC) $(HEADERS)
	$(ARDUINO_CLI) compile -e -p $(PROFILE) $(OPTIONS)

upload: build
	$(ARDUINO_CLI) upload -m $(PROFILE) -p $(PORT)

clean:
	$(ARDUINO_CLI) cache clean
	rm -Rf ./build/


.PHONY: all help build upload clean
