[env:ats-mini]
board = ats-mini
board_build.arduino.memory_type = qio_opi
board_build.partitions = custom_16Mb.csv
build_src_filter = ${env.build_src_filter} +<../boards/ats-mini>
build_unflags = -flto
build_flags =
    ${env.build_flags}
    -Iboards/ats-mini
    -DDEVICE_NAME='"Bruce ATS Mini"'
    ; No radio pins - radio not used
