[env:ats-mini]
board = ats-mini
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.partitions = partitions/ats-mini.csv
build_src_filter = ${env.build_src_filter} +<../boards/ats-mini>
build_flags =
    ${env.build_flags}
    -Iboards/ats-mini
    -DDEVICE_NAME='"Bruce ATS Mini"'
    -DSMOOTH_FONT=1
    ; No radio pins - radio not used
